#!/usr/bin/env python3
"""Freeze library/**/*.asm.json into a shippable Python module.

The distribution ships flat modules (no package dir for the JSON to ride in),
so the 30-tool library is bundled into `_asm_library_data.py` as a plain module
that always imports. `library_select.load_library()` prefers the on-disk
library/ directory (so dev edits are live) and falls back to this bundle when
installed. Run before building the wheel; the generated file is committed.
"""
from __future__ import annotations

import glob
import json
import pprint
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LIB = ROOT / "library"
OUT = ROOT / "_asm_library_data.py"


def main() -> None:
    manifests = sorted(
        (json.loads(Path(p).read_text(encoding="utf-8"))
         for p in glob.glob(str(LIB / "**" / "*.asm.json"), recursive=True)),
        key=lambda m: m.get("service_id", ""),
    )
    # Python literals (True/False/None), not JSON — this is imported, not parsed.
    body = pprint.pformat(manifests, indent=1, width=100, sort_dicts=False)
    OUT.write_text(
        f'"""Auto-generated by build_library_bundle.py on {date.today()}. '
        f'Do not edit by hand — edit library/ and regenerate."""\n'
        f"# {len(manifests)} manifests frozen from library/\n"
        f"MANIFESTS = {body}\n",
        encoding="utf-8",
    )
    # fail loud if the emitted module isn't valid / round-trippable
    import ast
    parsed = ast.literal_eval(body)
    assert parsed == manifests, "bundle round-trip mismatch"
    print(f"wrote {OUT.name}: {len(manifests)} manifests")


if __name__ == "__main__":
    main()
